### ISSUE TITLE
Problemi sa reakcijom na koliziju

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-007-breakout#7]
Ugao pod kojim se loptica odbija bi trebalo preciznije izracunati. Igra je dovoljno jednostavna da bi mogla malo detaljnije da se implementira.

**Comment by martakrcakovic** [comment]
Podesen je ugao odbijanja loptice od lenjira u zavisnosti od kojeg dela lenjira se loptica odbila .
